### ISSUE TITLE
Trigger hardware buttons instead of spotify specific

### ISSUE THREAD

**Issue by jrschumacher** [jguice/mac-bt-headset-fix#15]
Could you catch the bluetooth commands and trigger the hardware buttons instead of Spotify specific commands?

See python script to trigger hardware buttons: https://gist.github.com/fredrikw/4078034

**Comment by jguice** [comment]
That was a long holiday ;)

Finally got this done!  Give the beta a try and let me know how it works for you:  https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/Spotify+Bluetooth+Headset+Listener.zip

**Comment by jrschumacher** [comment]
Haha! I have "holidays" like that too :) will check it out today.

**Comment by jrschumacher** [comment]
@jguice works like a charm!!

**Comment by jguice** [comment]
Yay!  Thanks for the testing help. :smiley_cat:

**Comment by jguice** [comment]
Hi, FYI I changed the next/prev ff/rw button mappings in the latest build.  This seems to map best to most headphone button functions. :)

**Comment by jrschumacher** [comment]
I'll test it later today.

**Comment by jrschumacher** [comment]
Works perfectly.

I'd suggest adding a log of some sort so a user can debug the app/bluetooth device:

![screen shot 2015-03-27 at 6 06 48 am](https://cloud.githubusercontent.com/assets/46549/6865913/530ba1e2-d449-11e4-85c5-15890abf60a3.png)

And other than some trivial elements:

- remove Spotify in name
- load on start option
- change icon when it receives input

![screen shot 2015-03-27 at 6 40 54 am](https://cloud.githubusercontent.com/assets/46549/6866193/4137527e-d44c-11e4-9067-2332a887f818.png)


Also post it to Apple Store (if they will take it) because I think you'd get some hits.

**Comment by jrschumacher** [comment]
I should also say. For me, $1.99 would be the sweet spot.

**Comment by jguice** [comment]
Hey, sorry for the delay replying. ;)

I switched jobs and things have been pretty chaotic but it's settling down
and I'm getting back into this project.

Thanks a ton for the info and icons!!  I didn't create the original icons
but clearly I need to recreate them as double-size retina versions.

I'll get these enhancements made and give it a shot!
