### ISSUE TITLE
Broken with 1.0.1.811.g63b21681

### ISSUE THREAD

**Issue by robbiet480** [jguice/mac-bt-headset-fix#17]
Using the latest Spotify open beta, the app no longer works. You can try out the beta [here](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Welcome-to-the-Desktop-Beta/td-p/932803). Don't worry, you can have both installed side by side without any extra work.

I'll try to fix this in the next few days.

**Comment by jguice** [comment]
Ah, awesome.  Thanks for the help!  I can take a look this weekend :)

**Comment by robbiet480** [comment]
Ok, well I found the issue at least, no idea how to fix it.

Upon starting Spotify Bluetooth Headset Listener, this line is output in my console:
`1/12/15 16:41:35.590 Spotify Bluetooth Headset Listener[93073]: warning: failed to get scripting definition from /Applications/Spotify.app; it may not be scriptable.`

I re-installed the Spotify non-beta version, and found that it had scripting definitions, whereas the beta had no scripting definitions at all. 

So I guess we need to find a new way to trigger commands... The only other interesting note is that when hitting any built-in keyboard shortcuts for media, there are "key codes" (don't know what they are really called) output into Console. I've seen `NX_KEYTYPE_PLAY`, `NX_KEYTYPE_REWIND`, `NX_KEYTYPE_FASTFORWARD`

**Comment by jguice** [comment]
Oh.  Hopefully that is just an omission from the beta bulid. ;)

If not then I guess it's time to do that rewrite I've been planning where I just re-fire the proper media key codes (still don't understand why the apple bluetooth stack doesn't do this).

**Comment by robbiet480** [comment]
I submitted some feedback to them in the beta app asking to re-add AppleScript support. We'll see what happens.

**Comment by johnelse** [comment]
Hello, sorry to butt in, but I came across this issue while searching for information about the same problem. You may be interested in [this](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434) workaround, which seems to get all the AppleScript commands other than `play track` working again.

Fortunately it looks like AppleScript support was broken by mistake rather than purposefully removed :)

**Comment by jguice** [comment]
Thanks! :)

**Comment by jguice** [comment]
Hi, I've updated the app to fire media key events (which should bypass the applescript problem).  Give it a shot and let me know!  https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/Spotify+Bluetooth+Headset+Listener.zip

**Comment by robnasby** [comment]
Works great for me.  Thanks for updating!!

**Comment by jguice** [comment]
Cool.  Thanks for testing!

**Comment by robbiet480** [comment]
Maybe too late now, but I also haven't had issues!

**Comment by jguice** [comment]
Hi, FYI I changed the next/prev ff/rw button mappings in the latest build.  This seems to map best to most headphone button functions. :)
