### ISSUE TITLE
BTHSControl

### ISSUE THREAD

**Issue by niftylettuce** [jguice/mac-bt-headset-fix#19]
See this! https://github.com/JamesFator/BTHSControl

Worked like a charm.

**Comment by jguice** [comment]
Hi :)

Does this replace the need for the mac-bt-headset-fix?

**Comment by niftylettuce** [comment]
Yes it does!!!

**Comment by niftylettuce** [comment]
Plz document in readme and put up a notice!

**Comment by jguice** [comment]
Cool, I'll test it out.  Thanks!

**Comment by jguice** [comment]
Hi, I'm not crazy about the approach of installing (as root!) a binary of unknown origin (and without source) as prescribed by [BTHS Control's install script](https://github.com/JamesFator/BTHSControl/blob/afad1c44bf1705d2cdf5c61614d073896c86311e/install.sh).

Also I've updated this app to fire media key events so it should work with any app that supports those now.  Give it a try:  https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/Spotify+Bluetooth+Headset+Listener.zip

I'll update the readme to include a reference to the other project as a possible alternative in any case.  Thanks for the info!
