### ISSUE TITLE
allow control of other apps besides spotify

### ISSUE THREAD

**Issue by jguice** [jguice/mac-bt-headset-fix#2]
Instead of sending events directly to the spotify app, trap bluetooth events and resend as simulated keyboard media key events if possible.

This should make the bluetooth controls work with other apps and will also avoid the need to disable iTunes events.

Alternatively (or as an interim step), have a user-selectable way to choose which app to send events to.

**Comment by Wraithers** [comment]
Hi there, any luck getting this to work with the media keys? :smile: 

I'm using BeardedSpice to control playback across tabs, but pairing that with the ability to control it via my Bluetooth headset would be epic. Cheers :+1:

**Comment by jguice** [comment]
Hi, that rewrite is still a work in progress but I hope to have an alternate version firing media keys available for testing soon. :)

**Comment by Wraithers** [comment]
That's great to hear, looking forward to it :smiley:

**Comment by jguice** [comment]
Hey I finally did it! ;)

Try it out and let me know how it works for you:  https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/Spotify+Bluetooth+Headset+Listener.zip

**Comment by Wraithers** [comment]
Hey! It works great with BeardedSpice and I can now control YouTube and many other sites fine with my Jabra Rox Bluetooth headset :+1:

Do you think you could tell me where I'd need to tinker, and maybe even how, to make it fire specific keyboard commands? I'd love to make it fire 'Alt+Shift+P' to control playback on the Chrome extension Streamus, which is what I use mostly nowadays. For some reason Chrome Keyboard Shortcuts don't pick up media keys as inputs :disappointed:

**Comment by Wraithers** [comment]
Actually, I reinstalled Streamus, because I remember it came with the Media Keys preset as the keyboard shortcuts, and it worked, so in combination with your Bluetooth Headset Listener, I'm all set! Thanks a bunch! :smiley:

**Comment by jguice** [comment]
Excellent! :sunglasses:

**Comment by jguice** [comment]
Hi, FYI I changed the next/prev ff/rw button mappings in the latest build.  This seems to map best to most headphone button functions. :)
