### ISSUE TITLE
Not working on ﻿﻿﻿﻿﻿version ﻿﻿1.0.1.1060

### ISSUE THREAD

**Issue by alangalvino** [jguice/mac-bt-headset-fix#20]
After update Spotify to new version the program isn't working!

**Comment by jguice** [comment]
Just in case you haven't seen this...did you try this workaround yet?  https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434

**Comment by jguice** [comment]
Hi, I've released a new beta version that fires media key events (and should work with any apps that support them).  Can you try it and let me know if you're still having issues?  https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/Spotify+Bluetooth+Headset+Listener.zip

**Comment by alangalvino** [comment]
Hi, 

I tested the beta release, the play/pause button is working but the previous/next not working! Tested on Yosemite (10.10.2) and Spotify (1.0.1.1060.gc75ebdfd).

**Comment by jguice** [comment]
So on my headphones I have to push and hold the next/prev buttons for next/prev track functionality.

The mapping of which action on the headphones (press vs. press+hold) is next/prev and which is fast-forward/rewind doesn't seem to be consistent.

Try a push+hold and let me know.  Otherwise maybe there is a different keycode being sent.  I added log output for this and instructions too (run the console app) ;)

**Comment by alangalvino** [comment]
I have a bose ae2w and to trigger the next function i click twice on play/pause button to trigger the previous function i had to click three times play/pause button.

Holding a little after click work for me!

**Comment by jguice** [comment]
Ah!  yeah they're all a bit different it seems :wink: 

Well if you find a key that should do something but isn't check that console app and create an issue with the log entry (it has the codes I need to add support).  Also mention what the button is supposed to do and I'll see if I can add support.

**Comment by alangalvino** [comment]
Sure, thanks!

**Comment by jguice** [comment]
Hi, I've reversed the next/prev and ff/rw mappings in the latest build.  This seems to map best to most headphone button behaviors :)

**Comment by alangalvino** [comment]
I'll try it!

**Comment by alangalvino** [comment]
Works like a charm!
