### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by deadman36g** [jguice/mac-bt-headset-fix#29]
Is there a chance browser support could be added? I stream music mostly through my browser and the functions don’t seem to work for me (They work great in iTunes and VLC), 

I have test in the latest versions of Chrome, Safari, and Firefox.

**Comment by jguice** [comment]
At this point the app literally captures bluetooth presses and replays them as media key presses.  Do the media keys on a mac keyboard work for your browser player?  If not then it's not very likely (the approach would vary by browser and website).  If the keyboard keys work then it could be some other issue in which case add which streaming site you're using here and I'll check it out.  Thanks!

**Comment by deadman36g** [comment]
Thanks for the reply jguice, br default the keyboard keys didn’t work for me either. I found an extension
https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen?hl=en, that seems to match the mac media keys with default key commands and thus works :)

**Comment by jguice** [comment]
Awesome!  I'll add it to the readme ;)
