### ISSUE TITLE
Add to brew cask

### ISSUE THREAD

**Issue by SteveEdson** [jguice/mac-bt-headset-fix#30]
Thanks for the app, its great. It'd be really handy if it was available to install with homebrew's cask though.

**Comment by jguice** [comment]
Will do this for the next version (currently in beta).  Thanks!

**Comment by michaelblyons** [comment]
I don't know much about [creating a cask,][1] but if I worked it out, could I submit on your behalf? Or do you want to do that yourself?

[1]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by hegelstad** [comment]
Its 2018 ⌛️

**Comment by curiositycasualty** [comment]
With the merge of https://github.com/Homebrew/homebrew-cask/pull/65939 this can be closed as fixed.

**Comment by SteveEdson** [comment]
If this is now supported, it should probably be mentioned in the readme?
