### ISSUE TITLE
Support for macOS Sierra

### ISSUE THREAD

**Issue by lawrence-m** [jguice/mac-bt-headset-fix#34]
The app appears to no longer function, as tested in macOS Sierra GM.

**Comment by Tronix117** [comment]
👍 
Same issue here

**Comment by vincentducorps** [comment]
Up @jguice :)

**Comment by jguice** [comment]
Gah!  Guess it's time for me to upgrade. 😉  (also I should really turn notification emails back on...thanks for the @mention @vincentducorps)

**Comment by Tronix117** [comment]
`[NSEvent addGlobalMonitorForEventsMatchingMask]` is not even called anymore on bluetooth key press :/ couldn't find a workaround yet.

**Comment by kolychev** [comment]
I'm not an expert here, but maybe my thoughts will help someone. If you check Console.app when press headset button, I see in console:
-----------
bluetoothaudiod		Pause
bluetoothaudiod	Signpost 1 AVRCP Pause
mediaremoted	Received broadcast command from client <private>: <private>
mediaremoted	No destination client can be found for command <private>, and the option to launch the app was not included. Dropping command.
bluetoothaudiod		Pause Release
-----------

The idea is to register the program as "mediaremoted client" somehow, so that daemon send button press events to that "client".

**Comment by FlorianBezagu** [comment]
Any news about this issue ?

**Comment by vincentducorps** [comment]
up, iTunes auto launch makes me insane ;)

**Comment by hdoria** [comment]
+1

**Comment by jguice** [comment]
Hi, finally got a dev environment setup for this and can of course replicate both iTunes autostart and broken media key "replay".  Thanks @Tronix117 and @kolychev for help with the research. 😉

I'll update this issue with my progress (and hopefully will have a new beta to try soon).

**Comment by jguice** [comment]
Hey, good news. 😀

I have a working prototype that's intercepting bluetooth key-presses and replaying them as media keys.  It also keeps iTunes from starting when it's running (and no more hacky unloading daemons via launchctl).

This new version is in swift (which I'm learning) and will ultimately be a complete re-write (again).  I should have a version up in the next week for testing.

**Comment by Tronix117** [comment]
That is a really good news :)
Traumatized by itunes, I don't even dare to put my headset on anymore !

Good job !

**Comment by hdoria** [comment]
Awesome news! Let me know if you need someone to test it.

**Comment by timouwerkerk** [comment]
Great news! looking forward to test it. Great job as well!

**Comment by jguice** [comment]
Happy Thursday! 🎉 

Here's that [Beta](https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix-beta/bubo.app.zip) (macOS Sierra 10.12.1 or higher only).  :neckbeard: 

Create issues for any problems/etc.

**Comment by Dachaz** [comment]
So far, it seems to work as expected.
Thank you very much!

**Comment by AlbertoFdzM** [comment]
Cool, working for me too. No more iTunes window on my screen.

Thanks!

**Comment by fleebzz** [comment]
Great ! Works way better.

I will just create a new issue because I have to press Play/Pause twice each time for action to be executed.

**Comment by petermnt** [comment]
Works as expected with Sony MDR-1000X and BeardedSpice, thanks!

**Comment by DanSchoppe** [comment]
Edit: Works as expected with Plantronics BeatBack Pro headphones.

Sorry about the earlier contents of this comment, I had accidentally built / tested with the master branch. Everything works as expected on the sierra branch. Thanks!

**Comment by jguice** [comment]
Excellent @DanSchoppe ! (I was going to ask that). 😉

**Comment by fosple** [comment]
Which function do you use @jguice to intercept bluetooth key-presses?
